language: go
sudo: false

script:
    # staticcheck only works for two newest go versions
    - if [[ "$(go version)" =~ go1.1[12] ]]; then go get honnef.co/go/tools/cmd/staticcheck && staticcheck ./... && echo "staticcheck complete"; fi
    - go vet ./...
    - go test -tags "alltests" -run Suite -coverprofile coverage.txt github.com/keybase/go-triplesec

go:
    - 1.7.x  # go testing suite support, which we use, was introduced in go 1.7
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - 1.12.x

after_success:
- bash <(curl -s https://codecov.io/bash)
