language: go
sudo: false

script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
  - golangci-lint run
  - go vet ./...
  - go test ./...

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

after_success:
- bash <(curl -s https://codecov.io/bash)
